apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nocodb
    app.kubernetes.io/managed-by: helm
    meta.helm.sh/release-name: nocodb
  name: nocodb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nocodb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nocodb
    spec:
      containers:
      - image: nocodb/nocodb:latest
        imagePullPolicy: Always
        name: web
        ports:
        - containerPort: 8080
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - image: postgres:14-alpine
        imagePullPolicy: Always
        name: db
        env:
          - name: "POSTGRES_PASSWORD"
            value: {{ .Values.db.password }}
          - name: "POSTGRES_USER"
            value: {{ .Values.db.user }}
          - name: "POSTGRES_DB"
            value: {{ .Values.db.name }}
        ports:
        - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: db-storage
      restartPolicy: Always
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-storage
status: {}
