apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nocodb
    app.kubernetes.io/managed-by: helm
    meta.helm.sh/release-name: nocodb
  name: db-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

