apiVersion: v1
kind: Service
metadata:
  labels:
    app: nocodb-svc
    app.kubernetes.io/managed-by: helm
    meta.helm.sh/release-name: nocodb
  name: nocodb-svc
  namespace: default
spec:
  ports:
  - name: 8080-8080
    nodePort: 32657
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nocodb-svc
  type: NodePort
status:
  loadBalancer: {}
